### PR TITLE
Generate dataObjectOf function while deprecating the DataObject function

### PR DESCRIPTION
**Pull request by gmariotti**
Backport of #110

### CODE REVIEW

**Comment by vietj** [comment]
it looks good to me, however I think we should document the data object helpers idioms in the documentation and say that data object have an helper function to create them from kotlin

**Comment by gmariotti** [comment]
I was thinking of doing something also for the suspending extensions in one of the next PR. At least having a README or similar at a project level and then figure it out how to have it documented in the website. This one is already a huge PR and the deprecation annotation will make the transition easier for people that use the old functions. What do you think?

**Comment by vietj** [comment]
I think it's fine this way, just create a couple of issues for the doc and we are good . Can you merge it ?

**Comment by gmariotti** [comment]
Sure. Thanks for the review @vietj

**Pull request merged**
