### PR TITLE
Upgrade to Kotlin 1.3.60

### PR DESCRIPTION
**Pull request by jponge**
Also upgraded the Kotlin coroutines library.

ReceiveChannelHandler had to be added a field and a method due to additions in ReceiveChannel.
These are internal APIs so I made them throw NotImplementedError (through TODO("...")) and all tests still pass so it doesn't seem to be on a typical call path.

### CODE REVIEW

**Comment by jponge** [comment]
I've had to implement this in `ReceiveChannelHandler` due to new internal APIs:

```kotlin
  @InternalCoroutinesApi
  override val onReceiveOrClosed: SelectClause1<ValueOrClosed<T>>
    get() = TODO("not implemented")

  @InternalCoroutinesApi
  override suspend fun receiveOrClosed(): ValueOrClosed<T> {
    TODO("not implemented")
  }
}
```

This makes the code compile, and the tests suite do not seem to exerce that call path.

**Comment by slinkydeveloper** [comment]
Can you check why it fails?

**Comment by jponge** [comment]
It worked on my machine so...

**Comment by vincentfree** [comment]
Kotlin updated to `1.3.61` containing fixes, the pull request hasn't been merged yet so maybe it's a good idea to update it to `1.3.61` before it does.

**Comment by vincentfree** [comment]
> I've had to implement this in `ReceiveChannelHandler` due to new internal APIs:
> 
> ```kotlin
>   @InternalCoroutinesApi
>   override val onReceiveOrClosed: SelectClause1<ValueOrClosed<T>>
>     get() = TODO("not implemented")
> 
>   @InternalCoroutinesApi
>   override suspend fun receiveOrClosed(): ValueOrClosed<T> {
>     TODO("not implemented")
>   }
> }
> ```
> 
> This makes the code compile, and the tests suite do not seem to exerce that call path.

I had to overcome this problem because I have the new 1.3.2 coroutines dependency in one of my applications.

I've added it like this:

```kotlin
override suspend fun receiveOrClosed(): ValueOrClosed<T> {
        return channel.receiveOrClosed()
    }
}
```
This way I was able to use Flow and create one form a Channel.

**Comment by jponge** [comment]
Thanks @vincentfree 

I've added delegation to both methods.

**Comment by AlexeySoshin** [comment]
I've attempted to merge with `master`:
https://github.com/vert-x3/vertx-lang-kotlin/pull/164

**Comment by AlexeySoshin** [comment]
@vietj Did it go out of sync again? :(

**Comment by vietj** [comment]
I will have a look rebasing this PR tomorrow

**Comment by AlexeySoshin** [comment]
Any update on that? :)

**Comment by vietj** [comment]
on it :-)

**Comment by vietj** [comment]
Cherry-picked in master, can you have a check @jponge @AlexeySoshin ?

**Comment by jponge** [comment]
LGTM

**Comment by AlexeySoshin** [comment]
Amazing! 
Now I can start looking at Kotlin 1.3.70 :)

**Pull request closed without merging**
