### PR TITLE
3.7 coroutines.1.2.0

### PR DESCRIPTION
**Pull request by gmariotti**
- Update Kotlin version to `1.3.30` kotlinx.coroutines to `1.2.1`
- Deprecated `cancel` methods in `ReceiveChannelHandler`, deprecated in kotlinx.coroutines since `1.2.0`.
- Fixed test to stop using `SendChannel.isFull`, deprecated in https://github.com/Kotlin/kotlinx.coroutines/issues/1053
- Generated kotlin extensions

TODO:
- Create PR in `vertx-codetrans`
- Open similar PR for `master`

### CODE REVIEW

**Comment by gmariotti** [comment]
The pipeline fails because of all the tests in `KotlinVerticleFactoryTest` related to `scriptVerticle*.kts` resources. They seem related to `VerticleScriptDefinition` but I don't have any clue on how to debug those tests. Can you help me @vietj?

**Comment by okou19900722** [comment]
you missed readme

**Comment by gmariotti** [comment]
@okou19900722 good catch. Do you know anything about the vertx-lang-kotlin-compiler tests?

**Comment by slinkydeveloper** [comment]
The problem in tests seem like an error related to this issue: https://youtrack.jetbrains.com/issue/KT-30679 They marked as resolved in kotlin 1.3.30, but it still doesn't work. I'm waiting for a reply in their bug tracker

**Comment by slinkydeveloper** [comment]
btw @gmariotti do you think we should investigate script support through [jsr-223](https://github.com/JetBrains/kotlin/tree/master/libraries/examples/kotlin-jsr223-local-example) or with [new script compiler apis](https://github.com/Kotlin/KEEP/blob/master/proposals/scripting-support.md)

**Pull request closed without merging**
