### PR TITLE
Generate coroutine methods

### PR DESCRIPTION
**Pull request by phiSgr**
This pull request generates suspending methods of the same name for methods that has `kind` `METHOD_FUTURE`.

I will add some tests and clean up the template file later.

I am new to pretty much everything in this pull request, please bear with me if I made some stupid mistakes.

### CODE REVIEW

**Comment by vietj** [comment]
@phiSgr are you still working on this PR ?

**Comment by phiSgr** [comment]
@vietj Not really, I don't have much time recently. But I will be glad to continue if you confirm what I wrote to be alright.

**Comment by vietj** [comment]
sure I will soon

**Comment by phiSgr** [comment]
@vietj I have cleaned up the code quite a bit. It is ready to be reviewed.

**Comment by phiSgr** [comment]
What's left for me to do for this to be merged? @vietj

**Comment by vietj** [comment]
I'm trying to understand the difference with this PR https://github.com/vert-x3/vertx-lang-kotlin/pull/59 can somebody elaborate ? is it duplicate ?

**Comment by phiSgr** [comment]
I think so. The point of that PR is to generate code without using MVEL, and now mine has ditched that too.

There are quite some differences in generated code and how the code is generated.

**Comment by vietj** [comment]
I think both are good and I will merge yours (I tossed a coin :-) ) and both of you can contribute further more when it's merged. So before doing a review is here what I think is missing:

- have vertx-lang-kotlin-coroutines be like today + the generator
- have vertx-lang-kotlin contain the actual generated code instead of having two modules that generates
- documentation

**Comment by phiSgr** [comment]
It seems that the second point is beyond the scope of this PR?

**Comment by vietj** [comment]
yes, I can take care of the merge in a single module myself after

**Comment by vietj** [comment]
so documentation and then I'll review it, I think that @okou19900722 can also help to review since you seem to be kotlin-ists

**Comment by okou19900722** [comment]
Perfect, I learned a lot.

**Comment by vietj** [comment]
@phiSgr any progress on the doc side ?

**Comment by phiSgr** [comment]
Translating Javadoc to KDoc will take me some time.

**Comment by vietj** [comment]
ok

**Comment by vietj** [comment]
perhaps @okou19900722 can contribute as well ?

**Comment by phiSgr** [comment]
@vietj I am not familiar with the subtleties of Javadoc vs KDoc, maybe I have missed something.

**Comment by vietj** [comment]
what's the current status ?

**Comment by phiSgr** [comment]
I have put documentation on the generated code, translating `@code` to backticks and `@link` to square brackets.

**Comment by vietj** [comment]
I think that must be good then.

I think also we need to discuss how to handle global level documentation, i.e about the coroutinified extension methods.

**Comment by phiSgr** [comment]
Do you mean documentation on the file level, a guide on vertx.io, or something in between?

**Comment by vietj** [comment]
yes, with examples that would be part of the coroutine guide

**Comment by phiSgr** [comment]
@vietj Do you think that one example is enough?

**Comment by vietj** [comment]
when I try to build the project I get:

```
[ERROR] [ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='io.vertx:vertx-lang-kotlin-coroutine-codegen:3.6.0-SNAPSHOT'}' and 'Vertex{label='io.vertx:vertx-lang-kotlin-coroutines:3.6.0-SNAPSHOT'}' introduces to cycle in the graph io.vertx:vertx-lang-kotlin-coroutines:3.6.0-SNAPSHOT --> io.vertx:vertx-lang-kotlin-coroutine-codegen:3.6.0-SNAPSHOT --> io.vertx:vertx-lang-kotlin-coroutines:3.6.0-SNAPSHOT @ 
[ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='io.vertx:vertx-lang-kotlin-coroutine-codegen:3.6.0-SNAPSHOT'}' and 'Vertex{label='io.vertx:vertx-lang-kotlin-coroutines:3.6.0-SNAPSHOT'}' introduces to cycle in the graph io.vertx:vertx-lang-kotlin-coroutines:3.6.0-SNAPSHOT --> io.vertx:vertx-lang-kotlin-coroutine-codegen:3.6.0-SNAPSHOT --> io.vertx:vertx-lang-kotlin-coroutines:3.6.0-SNAPSHOT -> [Help 1]
```

**Comment by vietj** [comment]
no, the correspoinding code should be moved rather in this module

**Comment by phiSgr** [comment]
Finally managed to run `mvn install` successfully after messing with the XMLs. I am really not maven-savvy. Sorry if I did something stupid.

**Comment by vietj** [comment]
it looks good from here, I will make some more work on the branch and merge it

**Comment by vietj** [comment]
actually I would like to have the code generator written in java and not in kotlin because it makes easier to integrate the generator in non vertx projects that will generate similar code, can you rewrite it in java isntead ?

**Comment by phiSgr** [comment]
Could you elaborate more on the possible use case? I do not see a scenario of using this generator, or a modified version of it, in a context outside Kotlin.
Besides, Kotlin itself is interoperable with Java.

**Comment by vietj** [comment]
look at https://github.com/reactiverse/reactive-pg-client

**Comment by phiSgr** [comment]
@vietj Great project, I will try that out in my own projects sometime.

I am not convinced we need to have the generator in Java, but I have yet to understand where in [pom.xml](https://github.com/reactiverse/reactive-pg-client/blob/master/pom.xml) defines the process of code generation.

It would be great if you can explain a bit on how the plugins(?) activate the code generators. I will then experiment on generating code in that project, while keeping the generator as it is. Thanks!

**Comment by vietj** [comment]
@phiSgr sure, I'll try to do my best and explain why it would be better to have the plugin written in Java than Kotlin.

currently the generation is trigger by an annotation processor (in vertx-codegen project), so the generator classes have to be on the compilation classpath (javac). This is the reason we want to have no extra dependencies on the generator path.

**Comment by phiSgr** [comment]
I believe having a `.class` compiled from Kotlin on the classpath is as good as having one compiled from Java? Or do you need the source files in Java too?

Even if I rewrite my generator in Java, I still rely on KotlinPoet to generate valid Kotlin code. There are going to be some extra dependencies.

**Comment by phiSgr** [comment]
Is being dependencies-free something good to have, or is it necessary for the generator to be used elsewhere?

**Comment by vietj** [comment]
some non vertx project uses generator (like the pg-client)

**Comment by phiSgr** [comment]
I just deleted the 6 Kotlin data object files in the reactive-pg-client project and ran `mvn install`. They are not regenerated.
If you can demonstrate the proper configuration for triggering code generation in that project, I will see if it is possible to do code generation with my Kotlin generator there.

(Did you just accidentally send your previous message?)

**Comment by vietj** [comment]
@phiSgr it was actually broken (see https://github.com/reactiverse/reactive-pg-client/issues/91) for a while and I fixed it (https://github.com/reactiverse/reactive-pg-client/commit/e299bf7d1ab7bd23ac32cba439af56b6e2f8e99e)

**Comment by phiSgr** [comment]
@vietj I am still perplexed as to how your fix works, but I can use the my generator in that project (https://github.com/phiSgr/reactive-pg-client/commit/73d13b9effe4b07a9856cb76c5db3d0b57e670f2).

If that is how it should work, I prefer keeping this code generator in Kotlin. Are there any downsides of that I am not seeing?

**Comment by vietj** [comment]
the other reason I prefer it in java is that there are committers on this project that know java better than kotlin (so it's easier to contribute) and also there is absolutely no interest to have this generator written in kotlin as the only kotlin we care about in this project is runtime execution

**Comment by vietj** [comment]
the same way that when the Scala generator will be moved from MVEL to classes, we don't want to have this generator written in Scala because it means only committers knowing Scala will be able to fix or improve the generator.

Keep in mind that when somebody contributes a small change in vertx-codegen and changes an API, this person has to contribute to all code generator this change.

**Comment by phiSgr** [comment]
I see, your last paragraph is a valid reason to want the generator in Java.
But I don't want to do a rewrite of a rewrite again.
We may have to wait for a new contributor for this task, sorry for that.

**Comment by oripwk** [comment]
Hi,

What work is left to finish this PR and how can we help promote this?

It's a very important feature for Vert.x-Kotlin integration

**Comment by vietj** [comment]
it actually has been contributed by @okou19900722 , you can test it from OSS snapshot repository

**Comment by vietj** [comment]
let me close this for more clarity

**Comment by vietj** [comment]
you can use it and provide feedback @oripwk

**Comment by vietj** [comment]
also examples ,etc...

**Pull request closed without merging**
