### PR TITLE
 only the verticle with kt or kts suffix needs to be compiled

### PR DESCRIPTION
**Pull request by okou19900722**
like GroovyVerticleFactory and ScalaVerticleFactory

### CODE REVIEW

**Comment by vietj** [comment]
can you add a test with a `.kts` file ?

**Comment by okou19900722** [comment]
I am not very clear about the compilation process of kts files, because I have always used kotlin as java in use, not as a script. Maybe others can provide more help

**Comment by vietj** [comment]
@gmariotti can you hint here ?

**Comment by okou19900722** [comment]
`jsr223` is an existing feature. I wonder if the kts file will be like a kt file. When it is packaged, it will be compiled by the kotlin plugin.So if the kts file is not compiled, then it should not  require a test for kts file.
 @vietj  @gmariotti

**Comment by gmariotti** [comment]
Sorry @okou19900722 , I honestly didn't find a lot of info on `kts` files. However, except for the Kotlin Gradle DSL, I haven't see a lot of cases where `kts` was used, so I'm not really sure if it makes sense to support this format at all. What do you think @vietj?

**Comment by chengenzhao** [comment]
Any updates about this pr?
Should we merge this pr first and deal with kts suffix/prefix later?

**Comment by tsegismont** [comment]
Compiler not supported anymore #166

**Pull request closed without merging**
