### PR TITLE
init kotlin coroutines.

### PR DESCRIPTION
**Pull request by stream1984**
Init kotlin coroutine
Signed-off-by: stream <stream1984@gmail.com>

### CODE REVIEW

**Comment by vietj** [comment]
will have a look soon :-) now rxjava2 has been merged

**Comment by stream1984** [comment]
@vietj ping

**Comment by vietj** [comment]
@stream1984 when I try to build I get:

```
[ERROR] Failed to execute goal on project vertx-lang-kotlin-coroutine: Could not resolve dependencies for project io.vertx:vertx-lang-kotlin-coroutine:jar:3.5.0-SNAPSHOT: Could not find artifact org.jetbrains.kotlinx:kotlinx-coroutines-core:jar:0.16 in sonatype-nexus-releases (https://oss.sonatype.org/content/repositories/releases) -> [Help 1]
```

**Comment by vietj** [comment]
org.jetbrains.kotlinx is not in maven central but in bintray jcenter

**Comment by stream1984** [comment]
It is true, I would add commit to fix such deps and version.

**Comment by stream1984** [comment]
@vietj Review please.  :)

**Comment by vietj** [comment]
@stream1984 I'm currently reviewing and evaluating the solution, it will take some time, but don't worry it's one of my priorities at the moment :-)

**Comment by stream1984** [comment]
@vietj Thanks

**Comment by vietj** [comment]
can you rather use this for the dependency:

```
  <profiles>
    <profile>
      <id>jcenter</id>
      <activation>
        <property>
          <name>!skipJCenter</name>
        </property>
      </activation>
      <repositories>
        <repository>
          <id>central</id>
          <url>http://jcenter.bintray.com</url>
        </repository>
      </repositories>
    </profile>
  </profiles>
```

this will work with Maven Central validation rules.

**Comment by vietj** [comment]
@stream1984 thanks, I'm going to contribute on your PR, can you push your branch in this repo so we can collaborate on this ?

**Comment by vietj** [comment]
@stream1984 I've pushed this branch https://github.com/vert-x3/vertx-lang-kotlin/tree/stream1984-kotlin-coroutine-init based on your branch with a few modifications

- the `asyncResult` returns an element and not a deferred so inside a suspended function there is no need to await
- the `CoroutineVerticle` has been changed so `start` is _suspended_ by default
- I've added a function that turns a Vert.x `ReadStream` into a Kotlin `ReceiveChannel`

I'm currently implementing a function that turns a Vert.x `WriteStream` into a Kotlin `SendChannel` too but I need a bit more time to finish it.

**Comment by stream1984** [comment]
@vietj I have checkout this branch, and looks awesome.
I was thought a scene that someone wanna convert `Deferred` to `Future` by `fun <T> Deferred<T>.asFuture(): Future<T>`, should we consider it ?

**Comment by vietj** [comment]
yes it makes sense to me.

**Comment by stream1984** [comment]
> the asyncResult returns an element and not a deferred so inside a suspended function there is no need to await
So should we change it back ? user could make a chose for `await()` or `asFuture()`

**Comment by vietj** [comment]
@stream1984 no, watch this talk from Roman Elizarov https://vimeo.com/222499934#t=1514 and you will understand why we need to use it.

**Comment by stream1984** [comment]
Got it.

**Comment by vietj** [comment]
@stream1984 one thing you can look at is to rewrite `fun <T> asyncResult(timeout: Long, unit: TimeUnit = TimeUnit.MILLISECONDS, block: (h: Handler<AsyncResult<T?>>) -> Unit)` so that it is a suspending function, also I think we should use Vertx timer and not the Kotlin timer.

**Comment by stream1984** [comment]
I have notice that :)

**Comment by vietj** [comment]
@stream1984 I've made progress on the branch and reworked several aspects

* the coroutine builder is now based on Executor as it eases the integration with timeout (less needs to use unstable code)
* removed the timeout overloading as now the coroutine context handles scheduling with vertx
* replace vertx singleton by extension method
* rework the handler to channel adapter to reuse the `ReadStream` / channel adaptor

there are a couple of concerns:

* should we try to store the `VertxCoroutineDispatcher` as a context item ?
* the actual VertxCoroutineDispatcher does not trampoline when the current thread it the event loop and I am not sure we should do that (i.e we should always do a `runOnContext`)

**Comment by stream1984** [comment]
@vietj  Looks great.
> should we try to store the VertxCoroutineDispatcher as a context item ?
the actual VertxCoroutineDispatcher does not trampoline when the current thread it the event loop and I am not sure we should do that (i.e we should always do a runOnContext)
I think we could remove store of `VertxCoroutineDispatcher`.

There are a  lot of doesn't implemented methods, how to deal with them?

**Comment by vietj** [comment]
@stream1984 I think these methods are not used by Kotlin coroutines, but we could implement them

**Comment by vietj** [comment]
also @stream1984 I'm wondering why:

```
  require(isEventLoopContext, { "Not on the vertx eventLoop." })
```

I believe it would be fine if there is no context or in a worker verticle ? (probably not on a multithreaded verticle though)

**Comment by stream1984** [comment]
@vietj 
It was need before make extension on `Vertx` by `vertx.runCoroutine`, we could remove such checking now.

**Comment by stream1984** [comment]
@vietj 
I can not found extension of `vertx.delegate.runCoroutine` which show on the RxTest. Did you commit it?

**Comment by vietj** [comment]
@stream1984 you need to use the RxJava Vert.x API

**Comment by stream1984** [comment]
@vietj 
my IDE fault.  :)

**Comment by vietj** [comment]
I've written the documentation+example for channels and added a note for RxJava + added more tests.

I believe it should be ok to be reviewed and merged soon.

**Comment by stream1984** [comment]
Looks goode for me.

**Comment by vietj** [comment]
Actual PR is here https://github.com/vert-x3/vertx-lang-kotlin/pull/27 - closing this one

**Pull request closed without merging**
