### PR TITLE
 Rewrite vertx-lang-kotlin generator without MVEL

### PR DESCRIPTION
**Pull request by okou19900722**
https://github.com/vert-x3/issues/issues/367

### CODE REVIEW

**Comment by okou19900722** [comment]
@vietj hi, please take a look

**Comment by vietj** [comment]
that's a great contribution, I'll review it asap

**Comment by okou19900722** [comment]
it's OK now

**Comment by vietj** [comment]
I think you manually fixed it and did not fix the generator which does not work

**Comment by okou19900722** [comment]
I suspect that this is a problem with Doc.toHtml. It differs from the logic in common-lib. I have marked `--` before and after like this:
```java
      writer.print(" *--\n");
      doc.toHtml(" *", KotlinCodeGenHelper::renderLinkToHtml, "\n", writer);
      writer.print("--\n");
```
Some of the results are like this, 
```java
/*
 *--
 * Options for configuring the AmqpBridge.
 *--
 */
```
some are like this
```java
/*
 *--
 * Circuit breaker configuration options. All time are given in milliseconds.--
 */
```

**Comment by vietj** [comment]
where the fix should be ? in the new version of toHTML ?

**Comment by vietj** [comment]
can you provide a patch for vertx-codegen that fixes it ?

**Comment by okou19900722** [comment]
https://github.com/vert-x3/vertx-codegen/pull/189

**Pull request merged**
