### PR TITLE
Kotlin 1.3.61

### PR DESCRIPTION
**Pull request by AlexeySoshin**
Update `kotlin-1.3.60` branch from `master` to be able to merge.

### CODE REVIEW

**Comment by vietj** [comment]
can you check that this update will not break the vertx-stack project ?

i.e you install a snapshot of this and then you clone the vert-x3/vertx-stack project and built it with `mvn install -DskipNpm -DskipDocker`

**Comment by AlexeySoshin** [comment]
> can you check that this update will not break the vertx-stack project ?
> 
> i.e you install a snapshot of this and then you clone the vert-x3/vertx-stack project and built it with `mvn install -DskipNpm -DskipDocker`

I'll take a look into it. But how do I use a local version in the first place?

**Comment by vietj** [comment]
you install first this project locally and then use other snapshots

**Comment by AlexeySoshin** [comment]
@vietj Kotlin dependencies pass now in `vertx-stack`, but there's a problem with other libraries:
```
Conflict detected for artifact com.github.ben-manes.caffeine:caffeine:jar - version 2.6.2 was already selected while io.vertx:vertx-camel-bridge:jar:4.0.0-SNAPSHOT depends on version 2.8.0
```
Would you like me to take a look into that?

**Comment by AlexeySoshin** [comment]
@jponge Could you take a look and merge this into your branch, maybe, so we won't diverge too much?

**Comment by AlexeySoshin** [comment]
@vietj More serious conflict is with `annotation-api`:
```
[INFO] |  +- com.github.docker-java:docker-java:jar:3.0.0:compile
[INFO] |  |  +- (com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.6.4:compile - omitted for conflict with 2.9.9)
[INFO] |  |  +- org.glassfish.jersey.connectors:jersey-apache-connector:jar:2.11:compile
[INFO] |  |  |  +- (org.apache.httpcomponents:httpclient:jar:4.3.1:compile - omitted for conflict with 4.5.3)
[INFO] |  |  |  +- org.glassfish.jersey.core:jersey-common:jar:2.11:compile
[INFO] |  |  |  |  +- (javax.ws.rs:javax.ws.rs-api:jar:2.0:compile - omitted for duplicate)
[INFO] |  |  |  |  +- (javax.annotation:javax.annotation-api:jar:1.2:compile - omitted for conflict with 1.3.1)
```
As you can see the conflict is much deeper, and I'm not sure bumping versions will help there.

**Pull request merged**
