### PR TITLE
Add a Codegen Module to Add Coroutine Extensions to VertxGen

### PR DESCRIPTION
**Pull request by okou19900722**

### CODE REVIEW

**Comment by okou19900722** [comment]
it's a other implementation like #53 but without mvel

**Comment by vietj** [comment]
yes I will review after the first PR is merged

**Comment by phiSgr** [comment]
@okou19900722, in your code there is not handling for nullable types, as confirmed in the extensions generated for `NullableTCK`. But in the commit "generate extension" all the return types are nullable. I wonder if there is some magic that I do not see.

BTW, writing Kotlin to generate code is much more pleasant than writing MVEL. If I had known this is possible I would have used Kotlin too.

**Comment by okou19900722** [comment]
@phiSgr Yes, this is a recently added solution。When I was ready to do it and found that you had already done it, but now mvel is ready to remove it, so I rewritten it

https://github.com/vert-x3/issues/issues/367

**Comment by phiSgr** [comment]
I see. Thanks for pointing me to that.
It seems that you are not used to write Kotlin code, e.g. `filterIndexed { index, _ -> index < method.params.size - 1 }` can be replaced with `dropLast(1)`. If my PR is not going be merged anytime soon I can do the rewrite myself.

Another question, are we supposed to commit the generated code to the repository? @vietj

**Comment by vietj** [comment]
@phiSgr if we can avoid it, we should. I think for now it's in repo because it's in src/main/kotlin and there is no way to have it in the `target` dir and not confuse the IDE (idea). If we can work out a solution I'm all for it

**Comment by okou19900722** [comment]
I don't think there is a need for more than one module. People who use coroutines should prefer to use the suspend method.

**Comment by vietj** [comment]
so we could merge vertx-lang-kotlin-coroutines/vertx-lang-kotlin and vertx-lang-kotlin-codegen/vertx-lang-kotlin-coroutines-codegen right ?

**Comment by okou19900722** [comment]
Oh, I got it wrong, I thought you were saying that the code generated by vertx-lang-coroutine-code needs to be put together with vertx-lang-coroutines

**Comment by vietj** [comment]
@okou19900722 thanks for the contribution, have you signed the Eclipse Contributor Agreement ?

**Comment by vietj** [comment]
awesome @okou19900722 what your's email signing this ?

**Comment by okou19900722** [comment]
Why `vertx-lang-kotlin` was deleted

**Comment by vietj** [comment]
it has been moved here https://github.com/vert-x3/vertx-stack-generation/tree/master/vertx-lang-kotlin

**Comment by okou19900722** [comment]
Yes, I saw it, but why put the suspend method in `vertx-lang-kotlin` instead of `vertx-lang-kotlin-coroutines`

**Comment by okou19900722** [comment]
We discussed this issue before. If a programmer only wants to use dsl of DataObject, then he depends on `vertx-lang-kotlin`. If he wants to use coroutines, he will depends on `vertx-lang-coroutines`, but suspend methods depends on coroutines

**Comment by vietj** [comment]
because vertx-lang-kotlin is now the place where the code generation happens if we don't do that then we get two jars that uses the same package and we run into a split package issue with Java 9.

**Comment by okou19900722** [comment]
Yes, this seems to be a serious problem, Should we change the package name?, the current package name is generate by 'translateName ("kotlin")' and we can replace it with other strings instead `kotlin`

**Comment by vietj** [comment]
no we won't change that and keep a single jar instead, the dependency is optional, so it does force a dependency to the user

**Pull request merged**
