### PR TITLE
Updated Kotlin version and fixed compiler usage

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Cherry picked from #139 and adapted to master

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
This should be ported to 3.8 branch

**Comment by vietj** [comment]
before checking that in, did you check that the vertx-stack project still builds fine with it ?

**Comment by slinkydeveloper** [comment]
@vietj it builds fine. there is an issue in the stack tests but with a templating engine, not correlated to kt stuff

**Comment by okou19900722** [comment]
should we backported to 3.8 ? 
And maybe this pr would be add to milestones 4.0 not 3.8

**Comment by slinkydeveloper** [comment]
@okou19900722 I'm doing it :smile:

**Comment by slinkydeveloper** [comment]
when we backport the milestone is the first release, in this case i backport to vertx 3.8 so milestone is 3.8

**Comment by okou19900722** [comment]
👍

**Pull request merged**
