### PR TITLE
Add Testing Guide

### PR DESCRIPTION
**Pull request by napperley**
Kotliners (Kotlin developers) using Vert.x don't have a clear way to do testing. The new testing guide provides guidance on how to test Vert.x code that is **Kotlinic** (idiomatic Kotlin). Currently the guide is a draft version and hasn't been converted to AsciiDoc. More important to ensure that the approach for the guide is correct **before** getting the formatting right.

### CODE REVIEW

**Comment by vietj** [comment]
very nice, however we need to think about how to include it in the actual web-site doc, here is a preview : http://www.julienviet.com/vertx-3.5.0/docs/

**Comment by napperley** [comment]
Appears that all the docs on the Vert.x website are connected to a library. In order to convert the guide to website documentation it would need to be connected to a library. Would make sense to create a new library called **vertx-kotlintest** that is managed in the [vertx-lang-kotlin](https://github.com/vert-x3/vertx-lang-kotlin) repository.

**Comment by vietj** [comment]
@napperley I think we should rather shoot a guide and make this in its own repo and link the web site to this repo and keep things simple without a deploy process.

**Comment by vietj** [comment]
something like : vertx-guide-for-kotlin-devs

**Comment by napperley** [comment]
Do you have in mind a Kotlin Test example (using Vert.x)? So create a new repository in [vertx-examples](https://github.com/vert-x3/vertx-examples) called **kotlintest-example**.

**Comment by vietj** [comment]
@napperley yes

**Comment by vietj** [comment]
you can contribute examples on this branch https://github.com/vert-x3/vertx-examples/tree/3.5.0-staging . in this same branch I shall contribute soon coroutine example

**Comment by vietj** [comment]
@napperley I've flushed the coroutines example and the kotlin example reorg : https://github.com/vert-x3/vertx-examples/tree/3.5.0-staging/kotlin-examples/ so you could make a project for testing best practices in this directory along with web and test

**Comment by napperley** [comment]
In the process of setting up a new directory (Gradle project via Gradle Kotlin DSL) in **kotlin-examples**. Going to be a bit of a delay setting up the project since IntelliJ only recognises the Maven projects. Gradle works fine via the terminal which is a bit annoying since there is some context switching involved.

**Comment by vietj** [comment]
some projects in vertx-examples use gradle, so you don't need to contribute with gradle, for instance kotlin-examples/web uses it. the coroutines use maven because I'm used to it, however I wouldn't mind  it uses gradle

**Comment by vietj** [comment]
@napperley how are you going to contribute this ? as an example or as a guide ?

**Comment by napperley** [comment]
@vietj - As an example. Refer to this PR: https://github.com/vert-x3/vertx-examples/pull/236

**Pull request closed without merging**
